version: '3'
services:
  api:
    image: docker-express
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/html/node-docker

  web-cli:
    image: docker-express
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge